-- Keep the existing client key for idempotent draft replay, while adding a
-- database-level guard for the business identity of a task. Existing rows are
-- assigned an id-based legacy fingerprint so this migration never collapses
-- historical data implicitly; new publish transactions write the canonical
-- fingerprint generated by the need-publishing domain module.
ALTER TABLE "NeedTaskV2"
  ADD COLUMN "semanticFingerprint" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "fingerprintVersion" INTEGER NOT NULL DEFAULT 1;

UPDATE "NeedTaskV2"
SET "semanticFingerprint" = 'legacy:' || "id"
WHERE "semanticFingerprint" = '';

CREATE UNIQUE INDEX "NeedTaskV2_needId_semanticFingerprint_key"
  ON "NeedTaskV2"("needId", "semanticFingerprint");
