import type { Lang } from "@/domain/lang/types";

const en = {
  modal: { welcome: "Welcome to PetNido", signInOrSignup: "Sign in or create an account to continue", closeDialog: "Close sign-in dialog", continueWithEmail: "Continue with email", continueGoogle: "Continue with Google", continueLine: "Continue with LINE", termsAgreement: "By continuing, you agree to the", terms: "Terms of Service", and: "and", privacy: "Privacy Policy", loginTitle: "Sign in", signOut: "Sign out", email: "Email address", password: "Password", cancel: "Cancel", checking: "Checking…", login: "Sign in", loginSuccess: "Signed in successfully", invalidPassword: "Enter your password", invalidCredentials: "The email or password is incorrect.", networkError: "A network error occurred.", signupTitle: "Create an account", username: "Nickname", signupPassword: "Password", signup: "Create account", registering: "Creating…", emailSendFailed: "We could not send the email. Check the address and try again.", serverError: "A server error occurred. Please try again.", emailLogin: "Continue with email", invalidEmail: "Enter a valid email address.", unexpectedError: "Something unexpected happened.", verifyTitle: "Verify your email", verifyDescription: "Enter the six-digit code sent to your email. The code expires soon.", resend: "Resend code", resendIn: "Resend in {n}s", confirming: "Verifying…", confirm: "Verify", sending: "Sending…", codeInvalid: "The verification code is incorrect.", codeExpired: "The verification code has expired. Request a new one.", attemptsExceeded: "Too many incorrect codes. Request a new one.", rateLimited: "Too many attempts. Wait a moment and try again.", emailRegistered: "This email is already registered.", userCreateFailed: "The account could not be created.", genericError: "Something went wrong.", verifySuccess: "Email verified", verifyWelcome: "Welcome to PetNido!", forgotPassword: "Forgot password?" },
  passwordField: { label: "New sign-in password", hint: "Use at least 8 characters with at least one letter and one number.", invalid: "Use at least 8 characters with at least one letter and one number.", show: "Show password", hide: "Hide password" },
  accountUnlink: { loginPassword: "PetNido sign-in password", loginPasswordDescription: "Enter the password you use to sign in to PetNido with your email.", passwordRequired: "Enter your sign-in password.", passwordIncorrect: "The sign-in password is incorrect. Try again." },
  accountConnect: { connecting: "Opening Google…", startError: "Google connection could not be started. Try again.", title: "Confirm Google connection", description: "Confirm that you want to connect the selected Google account to your current PetNido account.", currentAccount: "Current account email", googleAccount: "Selected Google account", noEmail: "No email set", emailUnchanged: "Connecting Google only adds another sign-in method and does not change your current account email. Email-password sign-in and email notifications will continue to use your current account email.", confirm: "Connect Google", confirming: "Connecting…", cancel: "Cancel", close: "Close", success: "Google connected", alreadyLinked: "This Google account is already connected to your account.", accountInUse: "This Google account is connected to another PetNido account and cannot be connected again.", emailInUse: "This Google email belongs to another PetNido account. Choose a different Google account.", emailNotVerified: "The selected Google account does not have a verified email and cannot be connected.", expired: "This connection request has expired. Return to settings and try again.", genericError: "Google could not be connected. Try again.", boundEmail: "Google account: {email}" },
  lineConnect: { connecting: "Opening LINE…", startError: "LINE connection could not be started. Try again.", title: "LINE connection was not completed", success: "LINE connected", alreadyLinked: "This LINE account is already connected to your account.", accountInUse: "This LINE account is connected to another PetNido account and cannot be connected again.", expired: "This connection request has expired. Return to settings and try again.", genericError: "LINE could not be connected. Try again." },
  googleExisting: { unavailableTitle: "This Google sign-in cannot continue", unavailableBody: "The link has expired. Start again from sign in.", existingTitle: "A PetNido account already uses this email", existingBody: "Google email {email} is already registered. Verify that email to connect Google to the existing account.", verifyAndConnect: "Verify and connect", sending: "Sending…", code: "Verification code", confirmConnect: "Confirm connection", confirming: "Connecting…", cancel: "Cancel", sessionFailed: "The account was connected, but the sign-in session could not be created. Sign in again.", invalidCode: "The verification code is incorrect.", codeExpired: "The verification code has expired. Request a new one.", attemptsExceeded: "Too many incorrect codes. Request a new one.", rateLimited: "Too many attempts. Wait a moment and try again.", genericError: "Google could not be connected. Try again." },
  errorPage: { title: "Sign-in was not completed", configuration: "The sign-in service could not complete the callback. You are not signed in yet.", denied: "The sign-in request was cancelled or not authorized.", default: "Something went wrong while signing in. Please try again.", retry: "Try signing in again", home: "Return home" },
  forgotPassword: { title: "Reset password", description: "Enter your account email to receive a verification code.", completed: "Your password has been set. You can now sign in with your email and new password.", backToSignIn: "Return to sign in", cancel: "Cancel", email: "Email address", emailInvalid: "Enter a valid email address.", code: "Verification code", sendCode: "Send verification code", sending: "Sending…", verifyCode: "Verify code", verifying: "Verifying…", setPassword: "Set password", saving: "Saving…", invalidCode: "The verification code is incorrect.", codeExpired: "The verification code has expired. Request a new one.", attemptsExceeded: "Too many incorrect codes. Request a new one.", rateLimited: "Too many attempts. Wait a moment and try again.", genericError: "The password could not be reset. Try again." },
  setPasswordPage: { setTitle: "Set sign-in password", changeTitle: "Change sign-in password", description: "We will send a verification code to your current account email.", email: "Current account email", code: "Verification code", sendCode: "Send verification code", sending: "Sending…", verifyCode: "Verify code", verifying: "Verifying…", confirm: "Set password", changeConfirm: "Update password", changing: "Saving…", cancel: "Cancel", completed: "Your sign-in password has been updated.", backToSettings: "Return to settings", invalidCode: "The verification code is incorrect.", codeExpired: "The verification code has expired. Request a new one.", attemptsExceeded: "Too many incorrect codes. Request a new one.", rateLimited: "Too many attempts. Wait a moment and try again.", genericError: "The password could not be updated. Try again." },
  lineFirstUse: { title: "Do you already have a PetNido account?", connectExisting: "Connect an existing account", createNew: "I do not have an account — create a new one", creating: "Creating…", existingEmail: "Email of your existing account", code: "Verification code", sendCode: "Send verification code", sending: "Sending…", confirm: "Confirm connection", confirming: "Connecting…", back: "Back", errors: { INVALID_EMAIL: "Enter a valid email address.", INVALID_CODE: "The verification code is incorrect.", CODE_EXPIRED: "The verification code has expired. Request a new one.", TOO_MANY_CODE_ATTEMPTS: "Too many incorrect codes. Request a new one.", RATE_LIMITED: "Too many attempts. Please wait and try again.", EXISTING_ACCOUNT_NOT_FOUND: "No PetNido account with this verified email was found.", PROVIDER_ALREADY_LINKED: "That account already has another LINE sign-in connected.", LINE_ACCOUNT_ALREADY_IN_USE: "This LINE account already has activity and cannot be connected to another account.", SESSION_CREATE_FAILED: "The account was connected, but the sign-in session could not be updated. Sign in again.", DEFAULT: "The account could not be connected. Try again." } },
} as const;

const zh = {
  modal: { welcome: "欢迎来到 PetNido", signInOrSignup: "登录或创建账号后继续", closeDialog: "关闭登录对话框", continueWithEmail: "使用邮箱继续", continueGoogle: "使用 Google 继续", continueLine: "使用 LINE 继续", termsAgreement: "继续即表示你同意", terms: "服务条款", and: "和", privacy: "隐私政策", loginTitle: "登录", signOut: "退出登录", email: "邮箱地址", password: "密码", cancel: "取消", checking: "确认中…", login: "登录", loginSuccess: "登录成功", invalidPassword: "请输入密码", invalidCredentials: "邮箱或密码不正确。", networkError: "网络错误，请重试。", signupTitle: "创建账号", username: "昵称", signupPassword: "密码", signup: "注册", registering: "注册中…", emailSendFailed: "邮件发送失败，请检查邮箱地址。", serverError: "服务器错误，请稍后重试。", emailLogin: "使用邮箱登录", invalidEmail: "请输入有效的邮箱地址。", unexpectedError: "发生了意外错误。", verifyTitle: "验证邮箱", verifyDescription: "请输入发送到邮箱的 6 位验证码。验证码很快会过期，请及时输入。", resend: "重新发送", resendIn: "{n} 秒后重发", confirming: "验证中…", confirm: "确认", sending: "发送中…", codeInvalid: "验证码不正确。", codeExpired: "验证码已过期，请重新发送。", attemptsExceeded: "错误次数过多，请重新发送验证码。", rateLimited: "尝试次数过多，请稍后重试。", emailRegistered: "该邮箱已注册。", userCreateFailed: "账号创建失败。", genericError: "发生错误。", verifySuccess: "邮箱已验证", verifyWelcome: "欢迎来到 PetNido！", forgotPassword: "忘记密码？" },
  passwordField: { label: "新的登录密码", hint: "请至少输入 8 位，并且至少包含一个字母和一个数字。", invalid: "密码至少为 8 位，并且至少包含一个字母和一个数字。", show: "显示密码", hide: "隐藏密码" },
  accountUnlink: { loginPassword: "PetNido 登录密码", loginPasswordDescription: "请输入用于邮箱密码登录 PetNido 的密码。", passwordRequired: "请输入登录密码。", passwordIncorrect: "登录密码不正确，请重新输入。" },
  accountConnect: { connecting: "正在打开 Google…", startError: "无法开始绑定 Google，请重试。", title: "确认绑定 Google", description: "请确认要把所选 Google 账号绑定到当前 PetNido 账号。", currentAccount: "当前账号邮箱", googleAccount: "所选 Google 账号", noEmail: "未设置邮箱", emailUnchanged: "绑定后只会增加一种登录方式，不会修改当前的账号邮箱，邮箱密码登录和邮件通知依然使用当前账号邮箱。", confirm: "确认绑定", confirming: "绑定中…", cancel: "取消", close: "关闭", success: "Google 已绑定", alreadyLinked: "这个 Google 账号已经绑定到当前账号。", accountInUse: "这个 Google 账号已绑定到另一个 PetNido 账号，不能再次绑定。", emailInUse: "这个 Google 邮箱已属于另一个 PetNido 账号，请选择其他 Google 账号。", emailNotVerified: "所选 Google 账号没有已验证邮箱，无法绑定。", expired: "绑定请求已失效，请返回个人中心重新操作。", genericError: "无法绑定 Google，请重试。", boundEmail: "Google 账号：{email}" },
  lineConnect: { connecting: "正在打开 LINE…", startError: "无法开始绑定 LINE，请重试。", title: "LINE 绑定未完成", success: "LINE 已绑定", alreadyLinked: "这个 LINE 账号已经绑定到当前账号。", accountInUse: "这个 LINE 账号已绑定到另一个 PetNido 账号，不能再次绑定。", expired: "绑定请求已失效，请返回个人中心重新操作。", genericError: "无法绑定 LINE，请重试。" },
  googleExisting: { unavailableTitle: "此 Google 登录无法继续", unavailableBody: "链接已失效，请重新登录。", existingTitle: "此邮箱已有 PetNido 账号", existingBody: "Google 邮箱 {email} 已被使用。验证邮箱后，可将 Google 绑定到原账号。", verifyAndConnect: "验证并绑定", sending: "发送中…", code: "验证码", confirmConnect: "确认绑定", confirming: "绑定中…", cancel: "取消", sessionFailed: "账号已绑定，但登录状态创建失败，请重新登录。", invalidCode: "验证码不正确。", codeExpired: "验证码已过期，请重新发送。", attemptsExceeded: "验证码错误次数过多，请重新发送。", rateLimited: "尝试次数过多，请稍后重试。", genericError: "无法绑定 Google，请重试。" },
  errorPage: { title: "登录未完成", configuration: "登录服务暂时无法完成回调。这不是登录成功，请稍后重试。", denied: "登录请求已取消或没有获得授权。", default: "登录过程中发生错误，请重新尝试。", retry: "重新登录", home: "返回首页" },
  forgotPassword: { title: "找回密码", description: "输入账号邮箱，我们会向该邮箱发送验证码。", completed: "密码已设置，可以使用邮箱和新密码登录。", backToSignIn: "返回登录", cancel: "取消", email: "邮箱地址", emailInvalid: "请输入有效的邮箱地址。", code: "验证码", sendCode: "发送验证码", sending: "发送中…", verifyCode: "验证验证码", verifying: "验证中…", setPassword: "设置密码", saving: "保存中…", invalidCode: "验证码不正确。", codeExpired: "验证码已过期，请重新发送。", attemptsExceeded: "验证码错误次数过多，请重新发送。", rateLimited: "尝试次数过多，请稍后重试。", genericError: "无法重置密码，请重试。" },
  setPasswordPage: { setTitle: "设置登录密码", changeTitle: "修改登录密码", description: "验证码将发送到当前账号邮箱。", email: "当前账号邮箱", code: "验证码", sendCode: "发送验证码", sending: "发送中…", verifyCode: "验证验证码", verifying: "验证中…", confirm: "设置密码", changeConfirm: "更新密码", changing: "保存中…", cancel: "取消", completed: "登录密码已更新。", backToSettings: "返回设置", invalidCode: "验证码不正确。", codeExpired: "验证码已过期，请重新发送。", attemptsExceeded: "验证码错误次数过多，请重新发送。", rateLimited: "尝试次数过多，请稍后重试。", genericError: "无法更新登录密码，请重试。" },
  lineFirstUse: { title: "你已经有 PetNido 账号吗？", connectExisting: "绑定已有账号", createNew: "我没有账号，创建新账号", creating: "创建中…", existingEmail: "已有账号的邮箱", code: "验证码", sendCode: "发送验证码", sending: "发送中…", confirm: "确认绑定", confirming: "绑定中…", back: "返回", errors: { INVALID_EMAIL: "请输入有效的邮箱地址。", INVALID_CODE: "验证码不正确，请重新输入。", CODE_EXPIRED: "验证码已过期，请重新发送。", TOO_MANY_CODE_ATTEMPTS: "验证码错误次数过多，请重新发送。", RATE_LIMITED: "操作过于频繁，请稍后再试。", EXISTING_ACCOUNT_NOT_FOUND: "没有找到已验证该邮箱的 PetNido 账号。", PROVIDER_ALREADY_LINKED: "这个账号已经绑定了其他 LINE 登录方式。", LINE_ACCOUNT_ALREADY_IN_USE: "这个 LINE 账号已经产生业务数据，不能再绑定到其他账号。", SESSION_CREATE_FAILED: "账号已绑定，但登录状态更新失败，请重新登录。", DEFAULT: "绑定失败，请稍后重试。" } },
} as const;

const ja = {
  modal: { welcome: "PetNidoへようこそ", signInOrSignup: "ログインまたは新規登録を行ってください", closeDialog: "ログインダイアログを閉じる", continueWithEmail: "メールで続ける", continueGoogle: "Google で続ける", continueLine: "LINE で続ける", termsAgreement: "続行することで", terms: "利用規約", and: "および", privacy: "プライバシーポリシー", loginTitle: "ログイン", signOut: "ログアウト", email: "メールアドレス", password: "パスワード", cancel: "キャンセル", checking: "確認中…", login: "ログインする", loginSuccess: "ログインしました", invalidPassword: "パスワードを入力してください", invalidCredentials: "メールアドレスまたはパスワードが正しくありません。", networkError: "ネットワークエラーが発生しました。", signupTitle: "新規登録", username: "ユーザー名", signupPassword: "パスワード", signup: "登録する", registering: "登録中…", emailSendFailed: "メールの送信に失敗しました。メールアドレスをご確認ください。", serverError: "サーバーエラーが発生しました。しばらくしてからお試しください。", emailLogin: "メールでログイン", invalidEmail: "有効なメールアドレスを入力してください。", unexpectedError: "予期しないエラーが発生しました。", verifyTitle: "認証コード確認", verifyDescription: "メールに送信された6桁の認証コードを入力してください。コードの有効期限は数分です。", resend: "再送信", resendIn: "あと{n}秒", confirming: "確認中…", confirm: "確認する", sending: "送信中…", codeInvalid: "認証コードが正しくありません。", codeExpired: "認証コードの有効期限が切れています。再送してください。", attemptsExceeded: "入力回数の上限に達しました。コードを再送してください。", rateLimited: "試行回数が多すぎます。しばらく待ってから再試行してください。", emailRegistered: "このメールアドレスはすでに登録されています。", userCreateFailed: "ユーザーの作成に失敗しました。", genericError: "エラーが発生しました。", verifySuccess: "メール認証が完了しました", verifyWelcome: "ようこそ、PetNido へ！", forgotPassword: "パスワードをお忘れですか？" },
  passwordField: { label: "新しいログインパスワード", hint: "8文字以上で、英字と数字を1文字以上含めてください。", invalid: "パスワードは8文字以上で、英字と数字を1文字以上含めてください。", show: "パスワードを表示", hide: "パスワードを隠す" },
  accountUnlink: { loginPassword: "PetNido のログインパスワード", loginPasswordDescription: "メールとパスワードで PetNido にログインする際のパスワードを入力してください。", passwordRequired: "ログインパスワードを入力してください。", passwordIncorrect: "ログインパスワードが正しくありません。もう一度入力してください。" },
  accountConnect: { connecting: "Google を開いています…", startError: "Google 連携を開始できませんでした。もう一度お試しください。", title: "Google 連携の確認", description: "選択した Google アカウントを現在の PetNido アカウントに連携することを確認してください。", currentAccount: "現在のアカウントメール", googleAccount: "選択した Google アカウント", noEmail: "メール未設定", emailUnchanged: "連携後に増えるのはログイン方法だけで、現在のアカウントメールは変更されません。メール・パスワードでのログインとメール通知には、引き続き現在のアカウントメールが使われます。", confirm: "Google を連携", confirming: "連携中…", cancel: "キャンセル", close: "閉じる", success: "Google を連携しました", alreadyLinked: "この Google アカウントはすでに現在のアカウントに連携されています。", accountInUse: "この Google アカウントは別の PetNido アカウントに連携されているため、再度連携できません。", emailInUse: "この Google メールは別の PetNido アカウントで使用されています。別の Google アカウントを選択してください。", emailNotVerified: "選択した Google アカウントには確認済みメールがないため連携できません。", expired: "連携リクエストの有効期限が切れました。設定画面からもう一度お試しください。", genericError: "Google を連携できませんでした。もう一度お試しください。", boundEmail: "Google アカウント：{email}" },
  lineConnect: { connecting: "LINE を開いています…", startError: "LINE 連携を開始できませんでした。もう一度お試しください。", title: "LINE 連携が完了しませんでした", success: "LINE を連携しました", alreadyLinked: "この LINE アカウントはすでに現在のアカウントに連携されています。", accountInUse: "この LINE アカウントは別の PetNido アカウントに連携されているため、再度連携できません。", expired: "連携リクエストの有効期限が切れました。設定画面からもう一度お試しください。", genericError: "LINE を連携できませんでした。もう一度お試しください。" },
  googleExisting: { unavailableTitle: "この Google ログインは続行できません", unavailableBody: "リンクの有効期限が切れました。もう一度ログインしてください。", existingTitle: "このメールは既存の PetNido アカウントで使用されています", existingBody: "Google メール {email} はすでに登録されています。メールを確認すると、Google を既存アカウントに連携できます。", verifyAndConnect: "確認して連携", sending: "送信中…", code: "確認コード", confirmConnect: "連携を確定", confirming: "連携中…", cancel: "キャンセル", sessionFailed: "アカウントは連携されましたが、ログイン状態を作成できませんでした。もう一度ログインしてください。", invalidCode: "確認コードが正しくありません。", codeExpired: "確認コードの有効期限が切れています。再送してください。", attemptsExceeded: "確認コードの入力上限に達しました。再送してください。", rateLimited: "試行回数が多すぎます。しばらく待ってからお試しください。", genericError: "Google を連携できませんでした。もう一度お試しください。" },
  errorPage: { title: "ログインが完了しませんでした", configuration: "ログインサービスがコールバックを完了できませんでした。ログインはまだ完了していません。", denied: "ログインがキャンセルされたか、許可されませんでした。", default: "ログイン中にエラーが発生しました。もう一度お試しください。", retry: "もう一度ログイン", home: "ホームへ戻る" },
  forgotPassword: { title: "パスワードを再設定", description: "アカウントのメールアドレスを入力すると、確認コードを送信します。", completed: "パスワードを設定しました。メールアドレスと新しいパスワードでログインできます。", backToSignIn: "ログインへ戻る", cancel: "キャンセル", email: "メールアドレス", emailInvalid: "有効なメールアドレスを入力してください。", code: "確認コード", sendCode: "確認コードを送信", sending: "送信中…", verifyCode: "コードを確認", verifying: "確認中…", setPassword: "パスワードを設定", saving: "保存中…", invalidCode: "確認コードが正しくありません。", codeExpired: "確認コードの有効期限が切れています。再送してください。", attemptsExceeded: "確認コードの入力上限に達しました。再送してください。", rateLimited: "試行回数が多すぎます。しばらく待ってからお試しください。", genericError: "パスワードを再設定できませんでした。もう一度お試しください。" },
  setPasswordPage: { setTitle: "ログインパスワードを設定", changeTitle: "ログインパスワードを変更", description: "現在のアカウントメールに確認コードを送信します。", email: "現在のアカウントメール", code: "確認コード", sendCode: "確認コードを送信", sending: "送信中…", verifyCode: "コードを確認", verifying: "確認中…", confirm: "パスワードを設定", changeConfirm: "パスワードを更新", changing: "保存中…", cancel: "キャンセル", completed: "ログインパスワードを更新しました。", backToSettings: "設定へ戻る", invalidCode: "確認コードが正しくありません。", codeExpired: "確認コードの有効期限が切れています。再送してください。", attemptsExceeded: "確認コードの入力上限に達しました。再送してください。", rateLimited: "試行回数が多すぎます。しばらく待ってからお試しください。", genericError: "ログインパスワードを更新できませんでした。もう一度お試しください。" },
  lineFirstUse: { title: "すでに PetNido アカウントをお持ちですか？", connectExisting: "既存アカウントに連携", createNew: "アカウントを持っていないので新規作成", creating: "作成中…", existingEmail: "既存アカウントのメール", code: "確認コード", sendCode: "確認コードを送信", sending: "送信中…", confirm: "連携を確定", confirming: "連携中…", back: "戻る", errors: { INVALID_EMAIL: "有効なメールアドレスを入力してください。", INVALID_CODE: "確認コードが正しくありません。", CODE_EXPIRED: "確認コードの有効期限が切れました。再送してください。", TOO_MANY_CODE_ATTEMPTS: "確認コードの入力上限に達しました。再送してください。", RATE_LIMITED: "操作が多すぎます。しばらく待ってからお試しください。", EXISTING_ACCOUNT_NOT_FOUND: "この確認済みメールを持つ PetNido アカウントが見つかりません。", PROVIDER_ALREADY_LINKED: "このアカウントには別の LINE ログインがすでに連携されています。", LINE_ACCOUNT_ALREADY_IN_USE: "この LINE アカウントにはすでに利用履歴があるため、別のアカウントには連携できません。", SESSION_CREATE_FAILED: "アカウントは連携されましたが、ログイン状態を更新できませんでした。もう一度ログインしてください。", DEFAULT: "アカウントを連携できませんでした。もう一度お試しください。" } },
} as const;

export const authMessages = { en, zh, ja } satisfies Record<Lang, typeof en | typeof zh | typeof ja>;

export function getAuthMessages(lang: Lang) {
  return authMessages[lang];
}
